spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 指定date类型的格式化规则 format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 172.20.10.3
    port: 6379

# 使用nacos注册中心需要注意的就是 1 配置 nacos 2 就是配置nacos连接的地址 3 就是给服务起名称 要不就是注册不上
server:
  port: 20000

